# -*- coding: utf-8 -*-
"""TareaPendiente_inundada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hb0fo2hWO-lVLwmJV82QSBWPrKY6togC
"""

def calcular_agua_acumulada(terreno):
    pila = []
    agua_acumulada = []
    nivel = 0
    total_agua = 0

    for i, c in enumerate(terreno):
        if c == '/':
            pila.append((nivel, i))  #Busca en el terreno, conserva el nivel yguarda la posición.
            nivel += 1
        elif c == '\\': #Representamos un terreno y du nivel de agua, en este caso decentente, así que suma 1
            nivel -= 1
            if pila and pila[-1][0] > nivel:  # Terreno asendente, cierra el nivel.
                _, inicio = pila.pop()
                agua = i - inicio  # Calculamos la distancia
                total_agua += agua
                # Sumamos el agua de cada región.
                while agua_acumulada and agua_acumulada[-1][0] > inicio:
                    agua += agua_acumulada.pop()[1]
                agua_acumulada.append((inicio, agua))
        elif c == '_':
            pass  # planicie, no resta ni suma

    # Extraer solo las áreas de agua acumulada
    areas = [a[1] for a in agua_acumulada]

    # Imprimimos los datos de la consola
    print(total_agua)
    if areas:
        print(len(areas), *areas)
    else:
        print(0)


pendiente = r"\\///\_/\/\\\\/_/\\///__\\\_\\/_\/_/\/"


print("El agua de la pendiente es")
calcular_agua_acumulada(pendiente)